import type { Metadata } from "next";
import Nav from "@/components/site/Nav";
import Footer from "@/components/site/Footer";
import { contentPageGraph, jsonLdGraph } from "@/lib/jsonld";
import { absoluteUrl } from "@/lib/site";

const DESCRIPTION =
  "PaperCV has no accounts, no resume uploads, and no server-side storage. Here is exactly what data exists, where it lives, how to delete it, and who to contact.";

export const metadata: Metadata = {
  title: "Privacy: Your Resume Never Leaves Your Device",
  description: DESCRIPTION,
  alternates: { canonical: absoluteUrl("/privacy") },
};

export default function PrivacyPage() {
  return (
    <div className="bg-paper-50 text-ink-900">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: jsonLdGraph(
            contentPageGraph({
              path: "/privacy",
              name: "Privacy",
              description: DESCRIPTION,
              crumb: "Privacy",
            }),
          ),
        }}
      />
      <Nav />
      <main className="mx-auto max-w-3xl px-5 py-16">
        <h1 className="font-display text-[clamp(32px,5vw,50px)] tracking-tight">Privacy, in plain words</h1>
        <p className="mt-3 text-[13px] text-ink-400">Last updated: October 1, 2026</p>
        <div className="mt-7 space-y-8 text-[15px] leading-relaxed text-ink-600">
          <p>
            A resume contains your full name, phone number, address area, employment history, and often hints about
            your age and salary. That is some of the most sensitive personal data a web tool can touch, so PaperCV is
            built to never touch it.
          </p>

          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">What happens to your resume</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Everything you type is stored in your browser's local storage, on your device only.</li>
              <li>The PDF is generated by your browser, on your device. It is never uploaded, queued, or cached on a server.</li>
              <li>There are no accounts, so there is no profile of you anywhere.</li>
              <li>The JSON export is a file saved directly to your device; we never see it.</li>
              <li>
                If you arrive through a link like "/builder?name=...", the name travels in your own browser's address
                bar only, is written into your local draft, and is removed from the URL immediately. It is not logged
                by us and not sent anywhere.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">Cookies and tracking</h2>
            <p className="mt-3">
              PaperCV sets no cookies. The only browser storage used is the local storage entry that holds your
              resume draft, which is strictly necessary for the tool to work and stays on your device. There are no
              advertising trackers, no social pixels, no fingerprinting, and no third-party scripts: every file the
              site loads (fonts included) is served from this domain. As of the date above, no analytics are active.
              If privacy-respecting page analytics are enabled later, they will be cookieless and aggregate only
              (page views and country level), will never see resume content, and this page will be updated first.
            </p>
          </section>

          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">What the infrastructure sees</h2>
            <p className="mt-3">
              PaperCV is served as static files by Vercel Inc. (440 N Barranca Ave #4133, Covina, CA 91723, USA). Like
              any web host, Vercel processes standard server logs (IP address, user agent, requested URL) to deliver
              and secure the site; these logs are kept by Vercel under its own retention rules and may be processed in
              the United States. They concern page requests only: your resume content never appears in them because it
              never leaves your browser.
            </p>
          </section>

          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">How to delete your data</h2>
            <p className="mt-3">
              Click "New" in the builder to clear the stored resume, or clear this site's data in your browser
              settings. Because nothing exists outside your browser, that is a complete erasure; there is no copy to
              ask us to delete.
            </p>
          </section>

          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">Your rights, and who is responsible</h2>
            <p className="mt-3">
              PaperCV is published by Damien Yvert. Since the site collects no personal data server-side, requests
              for access, correction, or erasure are fulfilled directly on your device as described above. If you
              have any question about this policy, believe something behaves differently from what it says, or want
              to report a security issue, write to{" "}
              <a className="font-semibold text-brand-600 underline decoration-2 underline-offset-2" href="mailto:damienyvert.dev@gmail.com">
                damienyvert.dev@gmail.com
              </a>
              . Security researchers can also use the machine-readable contact at /.well-known/security.txt.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
