import type { Metadata } from "next";
import Nav from "@/components/site/Nav";
import Footer from "@/components/site/Footer";

export const metadata: Metadata = {
  title: "Privacy: Your Resume Never Leaves Your Device",
  description:
    "PaperCV has no accounts, no resume uploads, and no server-side storage. Here is exactly what data exists, where it lives, and how to delete it.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <div className="bg-paper-50 text-ink-900">
      <Nav />
      <main className="mx-auto max-w-3xl px-5 py-16">
        <h1 className="font-display text-[clamp(32px,5vw,50px)] tracking-tight">Privacy, in plain words</h1>
        <div className="mt-7 space-y-6 text-[15px] leading-relaxed text-ink-600">
          <p>
            A resume contains your full name, phone number, address area, employment history, and often hints about
            your age and salary. That is some of the most sensitive personal data a web tool can touch, so PaperCV is
            built to never touch it.
          </p>
          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">What happens to your resume</h2>
            <ul className="mt-3 list-disc space-y-2 pl-6">
              <li>Everything you type is stored in your browser's local storage, on your device only.</li>
              <li>The PDF is generated by your browser, on your device. It is never uploaded, queued, or cached on a server.</li>
              <li>There are no accounts, so there is no profile of you anywhere.</li>
              <li>The JSON export is a file saved directly to your device; we never see it.</li>
            </ul>
          </section>
          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">What the site itself collects</h2>
            <p className="mt-3">
              PaperCV is served as static files. Hosting (Vercel) keeps standard, aggregate request logs, and the
              site may use privacy-respecting, cookieless page analytics (page views and country level only, no
              resume content, no identifiers that follow you across sites). There are no advertising trackers, no
              social pixels, and no third-party scripts touching the builder.
            </p>
          </section>
          <section>
            <h2 className="font-display text-[26px] tracking-tight text-ink-900">How to delete your data</h2>
            <p className="mt-3">
              Click "New" in the builder to clear the stored resume, or clear this site's data in your browser
              settings. Because nothing exists outside your browser, that is a complete erasure; there is no copy to
              ask us to delete.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
